"""ParentStudentLink — stores parent-to-student relationships.

A parent user links to a student via a one-time invite code generated by the
teacher. The code is stored here until redeemed; after redemption the parent
and student are linked permanently (unless revoked).
"""

from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


class ParentInviteCode(Base):
    """One-time invite code generated by a teacher for a specific student.

    Lifecycle:
    1. Teacher calls POST /api/parents/invite-codes (creates this row).
    2. Parent redeems code via POST /api/parents/link (creates ParentStudentLink, marks used).
    3. Code cannot be reused after redemption.
    """

    __tablename__ = "parent_invite_codes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    code: Mapped[str] = mapped_column(String(12), unique=True, nullable=False, index=True)
    student_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    created_by: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    used_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"), nullable=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    student: Mapped["User"] = relationship("User", foreign_keys=[student_id])
    creator: Mapped["User"] = relationship("User", foreign_keys=[created_by])
    redeemer: Mapped["User | None"] = relationship("User", foreign_keys=[used_by])


class ParentStudentLink(Base):
    """Permanent link between a parent user and a student.

    Created when a parent successfully redeems a ParentInviteCode.
    A parent can be linked to multiple students (e.g., siblings).
    """

    __tablename__ = "parent_student_links"
    __table_args__ = (UniqueConstraint("parent_id", "student_id"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    parent_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    student_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    linked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    parent: Mapped["User"] = relationship("User", foreign_keys=[parent_id])
    student: Mapped["User"] = relationship("User", foreign_keys=[student_id])
