"""Demo-student seeding service (Issue #989 minimal version).

Creates N student accounts and a completed LearningSession for each,
so the 5/1 demo can show: classroom → assignment → student dashboard
→ completed report without any manual clicking.

Scope (minimal):
  - Only "completed" profile (one fixed good-student template)
  - Only fills fields the report page actually renders
  - NO per-step step_data, NO DialogueTurn/CharacterError rows
  - NO Vertex AI calls — ai_analysis is a hardcoded JSON template

Post-demo P2-P4 work (NOT implemented here):
  - Quality distribution (excellent/normal/weak buckets)
  - Realistic per-step step_data for vocab/comprehension
  - AI-generated ai_analysis via Vertex Gemini
"""
import json
import logging
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from ..auth.password import hash_password
from ..models.assignment import Assignment
from ..models.school import Classroom, ClassroomStudent
from ..models.session import LearningSession
from ..models.user import User
from ..schemas.admin_seed import DemoStudentSeedRequest, DemoStudentSeedResponse, SeededStudentInfo

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants — fixed "good student" profile for the demo
# ---------------------------------------------------------------------------

_DEMO_EMAIL_DOMAIN = "testdata.lingoleap.dev"

_ALL_STEPS: list[str] = [
    "reading_annotation",
    "live_tutor",
    "full_reading",
    "listening",
    "vocab_practice",
    "sentence_practice",
    "vocab_definition_match",
    "vocab_application",
    "comprehension_chat",
    "vocab_word_search",
    "knowledge_station",
]

_AI_ANALYSIS_TEMPLATE = json.dumps({
    "summary": "學生表現優良，朗讀流暢，理解能力達標。",
    "strengths": ["朗讀速度適中", "理解能力良好", "生字掌握度高"],
    "improvements": ["可以加強推論層次的回答"],
    "recommendation": "繼續保持，建議挑戰更高難度的課文。",
    "_note": "simulated — generated by demo seed",
}, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def seed_demo_students(
    db: Session,
    req: DemoStudentSeedRequest,
) -> DemoStudentSeedResponse:
    """Create demo students and completed sessions for a classroom.

    Idempotent for each email: if the email already exists we skip creating
    a new User but still create the session (unless one already exists).
    Returns info about whatever was created in this call.
    """
    classroom = db.query(Classroom).filter(Classroom.id == req.classroom_id).first()
    if classroom is None:
        raise ValueError(f"Classroom {req.classroom_id} not found")

    story_slug = _get_story_slug_for_classroom(db, req.classroom_id)

    seeded: list[SeededStudentInfo] = []

    for i in range(1, req.count + 1):
        num = str(i).zfill(2)
        email = f"{req.prefix}{num}@{_DEMO_EMAIL_DOMAIN}"
        name = f"{req.prefix.capitalize()}學生{num}"

        user = _get_or_create_student(db, email, name)
        _ensure_classroom_membership(db, classroom.id, user.id)
        session = _create_completed_session(db, user.id, classroom.id, story_slug)

        seeded.append(SeededStudentInfo(
            user_id=user.id,
            email=email,
            name=name,
            session_id=session.id,
        ))

    db.commit()

    logger.info(
        "demo_seed: created %d students in classroom %d (story_slug=%s)",
        len(seeded), req.classroom_id, story_slug,
    )

    return DemoStudentSeedResponse(
        classroom_id=req.classroom_id,
        students_created=len(seeded),
        sessions_created=len(seeded),
        students=seeded,
        story_slug=story_slug,
        note=(
            "Demo seed complete. "
            "All profiles use fixed good-student template. "
            "Full quality distribution is post-demo work."
        ),
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_story_slug_for_classroom(db: Session, classroom_id: int) -> str | None:
    """Return the first active assignment's story_slug, or None."""
    assignment = (
        db.query(Assignment)
        .filter(
            Assignment.classroom_id == classroom_id,
            Assignment.is_active == True,
        )
        .order_by(Assignment.created_at.asc())
        .first()
    )
    if assignment is None:
        return None
    if assignment.story_id is not None:
        return assignment.story_id
    if assignment.text_id is not None:
        return str(assignment.text_id)
    return None


def _get_or_create_student(db: Session, email: str, name: str) -> User:
    existing = db.query(User).filter(User.email == email).first()
    if existing is not None:
        return existing

    user = User(
        email=email,
        name=name,
        password_hash=hash_password("test1234"),
        is_active=True,
        email_verified=True,
        onboarding_completed=True,
    )
    db.add(user)
    db.flush()  # populate user.id without committing
    return user


def _ensure_classroom_membership(db: Session, classroom_id: int, student_id: int) -> None:
    exists = (
        db.query(ClassroomStudent)
        .filter(
            ClassroomStudent.classroom_id == classroom_id,
            ClassroomStudent.student_id == student_id,
        )
        .first()
    )
    if exists is None:
        db.add(ClassroomStudent(classroom_id=classroom_id, student_id=student_id))
        db.flush()


def _create_completed_session(
    db: Session,
    student_id: int,
    classroom_id: int,
    story_slug: str | None,
) -> LearningSession:
    """Create (or return existing completed) session for this student+story."""
    # Check for an existing completed session to stay idempotent
    existing = (
        db.query(LearningSession)
        .filter(
            LearningSession.student_id == student_id,
            LearningSession.classroom_id == classroom_id,
            LearningSession.status == "completed",
        )
        .first()
    )
    if existing is not None:
        return existing

    now = datetime.now(timezone.utc)

    session = LearningSession(
        student_id=student_id,
        classroom_id=classroom_id,
        story_slug=story_slug,
        status="completed",
        current_step=len(_ALL_STEPS),
        completed_at=now,
        # Reading metrics
        accuracy=85.0,
        overall_score=82.0,
        reading_result={
            "match_rate": 0.85,
            "accuracy": 85,
            "cpm": 120,
            "evaluation_method": "simulated",
            "feedback": "唸得很流暢！",
        },
        # 3-level comprehension scoring
        comprehension_score=80.0,
        literal_score=85.0,
        inferential_score=78.0,
        evaluative_score=75.0,
        comprehension_feedback="理解能力良好，推論層次可再加強。",
        # Step progress — current_step key + all steps completed
        step_progress={
            "current_step": "report",
            "steps_completed": _ALL_STEPS,
        },
        # Hardcoded AI analysis (no Vertex call for demo)
        ai_analysis=_AI_ANALYSIS_TEMPLATE,
    )
    db.add(session)
    db.flush()
    return session
