/**
 * Radical decomposition data for Chinese character education.
 * Based on 部件教學法 (component-based character teaching method)
 * advocated by Prof. Tseng Shih-chieh (曾世杰教授).
 *
 * Structure:
 *   - radicalMap: hand-curated radical data (highest priority)
 *   - charDecomposition: character → array of component breakdowns
 *   - radical-meanings.json: aggregated open-data fallback (v2.0 schema)
 *     Sources: moedict zh-TW (MOE open data) + makemeahanzi (LGPL) + branneman 214 radicals
 *     Generated by: scripts/build-radical-database.py
 */

export type RadicalRole = '形符' | '聲符' | '部件';

export interface RadicalInfo {
  /** Brief meaning of the radical */
  meaning: string;
  /** Semantic (形符) or phonetic (聲符) or generic component (部件) */
  role: RadicalRole;
  /** Characters that share this radical */
  relatedChars: RelatedChar[];
}

export interface RelatedChar {
  char: string;
  meaning: string;
}

export interface CharComponent {
  radical: string;
  role: RadicalRole;
  /** Short label shown in the decomposition display */
  label: string;
}

export interface CharDecomposition {
  /** Components that make up the character */
  components: CharComponent[];
  /** Plain-text decomposition formula, e.g. "氵 + 青" */
  formula: string;
  /** Data source: 'manual' | 'manual-override' | 'makemeahanzi' | 'chaizi' */
  source?: 'manual' | 'manual-override' | 'makemeahanzi' | 'chaizi';
}

// ---------------------------------------------------------------------------
// Radical database (常用部件庫)
// ---------------------------------------------------------------------------

export const radicalMap: Record<string, RadicalInfo> = {
  // Water-related
  '氵': {
    meaning: '與水有關',
    role: '形符',
    relatedChars: [
      { char: '清', meaning: '清澈，純潔' },
      { char: '河', meaning: '河流，水道' },
      { char: '海', meaning: '大海，廣闊的水域' },
      { char: '湖', meaning: '湖泊，陸地中的水體' },
      { char: '洗', meaning: '用水清洗' },
      { char: '泳', meaning: '游泳，在水中活動' },
      { char: '流', meaning: '流動，液體移動' },
      { char: '漂', meaning: '漂浮，輕輕浮在水面' },
    ],
  },
  '水': {
    meaning: '水，液體',
    role: '形符',
    relatedChars: [
      { char: '泉', meaning: '泉水，從地下湧出的水' },
      { char: '永', meaning: '永遠，長久' },
      { char: '冰', meaning: '冰，水結凍後的固體' },
    ],
  },

  // Sun/day-related
  '日': {
    meaning: '太陽，白天',
    role: '形符',
    relatedChars: [
      { char: '明', meaning: '光明，明亮' },
      { char: '晴', meaning: '天氣晴朗，陽光充足' },
      { char: '暗', meaning: '黑暗，光線不足' },
      { char: '時', meaning: '時間，時刻' },
      { char: '早', meaning: '早晨，時間靠前' },
      { char: '暖', meaning: '溫暖，令人舒適的溫度' },
      { char: '昨', meaning: '昨天，前一天' },
      { char: '春', meaning: '春天，一年中第一個季節' },
    ],
  },

  // Moon/month-related
  '月': {
    meaning: '月亮，月份',
    role: '形符',
    relatedChars: [
      { char: '明', meaning: '光明，明亮（日＋月）' },
      { char: '期', meaning: '期限，時間段落' },
      { char: '朝', meaning: '早晨；朝向' },
      { char: '朗', meaning: '明朗，清晰' },
    ],
  },

  // Wood/tree-related
  '木': {
    meaning: '樹木，木材',
    role: '形符',
    relatedChars: [
      { char: '樹', meaning: '樹木，植物' },
      { char: '林', meaning: '樹林，多棵樹' },
      { char: '森', meaning: '森林，茂密的樹林' },
      { char: '桌', meaning: '桌子，家具' },
      { char: '椅', meaning: '椅子，坐的家具' },
      { char: '板', meaning: '木板，平整的木材' },
      { char: '根', meaning: '根部，植物的基礎' },
    ],
  },

  // Grass/plant-related
  '艹': {
    meaning: '草木，植物',
    role: '形符',
    relatedChars: [
      { char: '花', meaning: '花朵，植物的花' },
      { char: '草', meaning: '草地，植物' },
      { char: '葉', meaning: '葉子，植物的葉片' },
      { char: '菜', meaning: '蔬菜，食用植物' },
      { char: '茶', meaning: '茶葉，飲料' },
      { char: '苦', meaning: '苦味，艱難' },
    ],
  },

  // Fire-related
  '火': {
    meaning: '火，熱',
    role: '形符',
    relatedChars: [
      { char: '炎', meaning: '火焰，炎熱' },
      { char: '烤', meaning: '烤熟，加熱食物' },
      { char: '燈', meaning: '燈光，照明工具' },
      { char: '焦', meaning: '燒焦，過度加熱' },
    ],
  },
  '灬': {
    meaning: '火，熱（底部形狀）',
    role: '形符',
    relatedChars: [
      { char: '熱', meaning: '高溫，炎熱' },
      { char: '煮', meaning: '烹煮，加熱食物' },
      { char: '熟', meaning: '煮熟，成熟' },
      { char: '照', meaning: '照射，光線照耀' },
      { char: '煙', meaning: '煙霧，燃燒產生的氣體' },
    ],
  },

  // Metal/gold-related
  '金': {
    meaning: '金屬，金錢',
    role: '形符',
    relatedChars: [
      { char: '銀', meaning: '銀，貴金屬' },
      { char: '鐵', meaning: '鐵，常見金屬' },
      { char: '錢', meaning: '錢，貨幣' },
      { char: '針', meaning: '針，細長的金屬物' },
      { char: '鑰', meaning: '鑰匙，開鎖的工具' },
    ],
  },

  // Earth/soil-related
  '土': {
    meaning: '土地，泥土',
    role: '形符',
    relatedChars: [
      { char: '地', meaning: '地面，土地' },
      { char: '城', meaning: '城市，有城牆的地方' },
      { char: '堆', meaning: '堆積，聚集在一起' },
      { char: '塊', meaning: '一塊，固體的一部分' },
    ],
  },

  // Person-related
  '人': {
    meaning: '人，人類',
    role: '形符',
    relatedChars: [
      { char: '從', meaning: '跟隨，從某處來' },
      { char: '眾', meaning: '眾多，很多人' },
      { char: '仁', meaning: '仁愛，善良' },
    ],
  },
  '亻': {
    meaning: '人，與人有關',
    role: '形符',
    relatedChars: [
      { char: '你', meaning: '你，第二人稱' },
      { char: '他', meaning: '他，第三人稱男性' },
      { char: '們', meaning: '複數後綴，如我們' },
      { char: '做', meaning: '做，製作，進行' },
      { char: '休', meaning: '休息，停止工作' },
      { char: '信', meaning: '信任，書信' },
      { char: '借', meaning: '借用，暫時使用' },
    ],
  },

  // Heart/mind-related
  '心': {
    meaning: '心，感情',
    role: '形符',
    relatedChars: [
      { char: '想', meaning: '思想，想念' },
      { char: '感', meaning: '感覺，情感' },
      { char: '愛', meaning: '愛，喜愛' },
      { char: '忘', meaning: '忘記，無法想起' },
    ],
  },
  '忄': {
    meaning: '心，感情（側旁）',
    role: '形符',
    relatedChars: [
      { char: '快', meaning: '快樂，速度快' },
      { char: '慢', meaning: '緩慢，速度不快' },
      { char: '情', meaning: '感情，情況' },
      { char: '恨', meaning: '恨，不喜歡' },
      { char: '怕', meaning: '害怕，恐懼' },
      { char: '忙', meaning: '忙碌，事情多' },
    ],
  },

  // Mouth-related
  '口': {
    meaning: '嘴巴，開口',
    role: '形符',
    relatedChars: [
      { char: '吃', meaning: '吃，進食' },
      { char: '喝', meaning: '喝，飲用液體' },
      { char: '唱', meaning: '唱歌，發出歌聲' },
      { char: '叫', meaning: '叫喊，呼叫' },
      { char: '說', meaning: '說話，表達' },
      { char: '問', meaning: '提問，詢問' },
      { char: '喜', meaning: '喜悅，高興' },
    ],
  },

  // Eye-related
  '目': {
    meaning: '眼睛，視覺',
    role: '形符',
    relatedChars: [
      { char: '看', meaning: '看，觀察' },
      { char: '眼', meaning: '眼睛' },
      { char: '睡', meaning: '睡覺，休眠' },
      { char: '盲', meaning: '看不見，失明' },
    ],
  },

  // Foot-related
  '足': {
    meaning: '腳，足夠',
    role: '形符',
    relatedChars: [
      { char: '跑', meaning: '跑步，快速移動' },
      { char: '跳', meaning: '跳躍，向上彈起' },
      { char: '踢', meaning: '用腳踢' },
      { char: '路', meaning: '道路，行走的地方' },
    ],
  },

  // Hand-related
  '手': {
    meaning: '手，動作',
    role: '形符',
    relatedChars: [
      { char: '拿', meaning: '拿取，用手持物' },
      { char: '打', meaning: '打，擊打' },
      { char: '推', meaning: '推動，施力移動' },
    ],
  },
  '扌': {
    meaning: '手，動作（側旁）',
    role: '形符',
    relatedChars: [
      { char: '打', meaning: '打，擊打' },
      { char: '拉', meaning: '拉，向自己方向施力' },
      { char: '推', meaning: '推，向外施力' },
      { char: '握', meaning: '握住，抓住' },
      { char: '提', meaning: '提起，拿著' },
      { char: '捉', meaning: '捉住，抓住' },
    ],
  },

  // Speech-related
  '言': {
    meaning: '說話，言語',
    role: '形符',
    relatedChars: [
      { char: '說', meaning: '說話' },
      { char: '話', meaning: '話語，語言' },
      { char: '語', meaning: '語言，話語' },
      { char: '詩', meaning: '詩歌，文學形式' },
    ],
  },
  '訁': {
    meaning: '說話，言語（側旁）',
    role: '形符',
    relatedChars: [
      { char: '說', meaning: '說話，表達意思' },
      { char: '話', meaning: '話語，說出的內容' },
      { char: '請', meaning: '請求，邀請' },
      { char: '謝', meaning: '感謝，表示謝意' },
      { char: '認', meaning: '認識，辨認' },
      { char: '識', meaning: '認識，知識' },
    ],
  },

  // Green/clear-related (phonetic example)
  '青': {
    meaning: '青色，清澈（聲旁）',
    role: '聲符',
    relatedChars: [
      { char: '清', meaning: '清澈，純潔（氵＋青）' },
      { char: '情', meaning: '感情，情況（忄＋青）' },
      { char: '晴', meaning: '晴天，天空無雲（日＋青）' },
      { char: '請', meaning: '請求，邀請（訁＋青）' },
      { char: '靜', meaning: '安靜，沒有聲音' },
    ],
  },

  // 文 character
  '文': {
    meaning: '文字，文化',
    role: '形符',
    relatedChars: [
      { char: '字', meaning: '文字，字詞' },
      { char: '句', meaning: '句子，一段話' },
    ],
  },

  // 力 strength
  '力': {
    meaning: '力量，努力',
    role: '形符',
    relatedChars: [
      { char: '勇', meaning: '勇敢，有膽量' },
      { char: '努', meaning: '努力，用力去做' },
      { char: '勤', meaning: '勤勞，認真努力' },
    ],
  },

  // Mountain
  '山': {
    meaning: '山，高地',
    role: '形符',
    relatedChars: [
      { char: '島', meaning: '島嶼，四面環水的陸地' },
      { char: '峰', meaning: '山峰，山的頂部' },
      { char: '峽', meaning: '峽谷，山間的通道' },
    ],
  },

  // Rain
  '雨': {
    meaning: '雨，天氣現象',
    role: '形符',
    relatedChars: [
      { char: '雪', meaning: '雪，白色的冰晶' },
      { char: '雲', meaning: '雲，天空中的水氣' },
      { char: '霧', meaning: '霧，低空的水氣' },
      { char: '雷', meaning: '雷，打雷的聲音' },
    ],
  },

  // Bird
  '鳥': {
    meaning: '鳥類，禽類',
    role: '形符',
    relatedChars: [
      { char: '鴨', meaning: '鴨子，水禽' },
      { char: '鵝', meaning: '鵝，大型水禽' },
      { char: '雞', meaning: '雞，家禽' },
    ],
  },

  // Child
  '子': {
    meaning: '孩子，小的',
    role: '形符',
    relatedChars: [
      { char: '好', meaning: '好，美好' },
      { char: '孩', meaning: '孩子，兒童' },
      { char: '孫', meaning: '孫子，後代' },
    ],
  },

  // Female
  '女': {
    meaning: '女性，女人',
    role: '形符',
    relatedChars: [
      { char: '媽', meaning: '媽媽，母親' },
      { char: '姐', meaning: '姐姐，年長的女性兄弟' },
      { char: '妹', meaning: '妹妹，年幼的女性兄弟' },
      { char: '她', meaning: '她，第三人稱女性' },
    ],
  },

  // 見 see
  '見': {
    meaning: '看見，視覺',
    role: '形符',
    relatedChars: [
      { char: '現', meaning: '現在，出現' },
      { char: '覺', meaning: '感覺，察覺' },
      { char: '視', meaning: '視覺，觀察' },
    ],
  },

  // ---------------------------------------------------------------------------
  // Issue #1099 — 熱門部件資料補齊（Top 50，relatedChars 以 57 課課文字頻排序）
  // ---------------------------------------------------------------------------

  // ⺼ flesh / body-radical variant of 肉
  '⺼': {
    meaning: '與身體、器官有關（肉字旁）',
    role: '形符',
    relatedChars: [
      { char: '育', meaning: '養育、教育' },
      { char: '肌', meaning: '肌肉' },
      { char: '背', meaning: '背部' },
      { char: '肯', meaning: '願意' },
      { char: '腦', meaning: '頭腦' },
      { char: '腳', meaning: '腳部' },
      { char: '腿', meaning: '腿部' },
      { char: '肩', meaning: '肩膀' },
    ],
  },

  // 阝 city (right) / mound (left)
  '阝': {
    meaning: '城邑或山丘（在字右為「邑」、在左為「阜」）',
    role: '形符',
    relatedChars: [
      { char: '都', meaning: '首都、都市' },
      { char: '部', meaning: '部分、部門' },
      { char: '阿', meaning: '稱謂字首' },
      { char: '隊', meaning: '隊伍' },
      { char: '除', meaning: '除去' },
      { char: '防', meaning: '防備' },
      { char: '陳', meaning: '陳列、姓氏' },
      { char: '陽', meaning: '太陽' },
    ],
  },

  // 貝 shell / money
  '貝': {
    meaning: '貝殼、古代錢幣；與財貨有關',
    role: '形符',
    relatedChars: [
      { char: '賽', meaning: '比賽' },
      { char: '員', meaning: '人員' },
      { char: '質', meaning: '品質' },
      { char: '資', meaning: '資源' },
      { char: '負', meaning: '背負、失敗' },
      { char: '則', meaning: '規則' },
      { char: '費', meaning: '費用' },
      { char: '敗', meaning: '失敗' },
    ],
  },

  // 王 king / jade
  '王': {
    meaning: '君王；也為「玉」的偏旁，與玉石有關',
    role: '形符',
    relatedChars: [
      { char: '現', meaning: '出現' },
      { char: '球', meaning: '球體' },
      { char: '理', meaning: '道理' },
      { char: '環', meaning: '環繞' },
      { char: '望', meaning: '希望、盼望' },
      { char: '珍', meaning: '珍貴' },
      { char: '玩', meaning: '玩耍' },
      { char: '玉', meaning: '美玉' },
    ],
  },

  // ⺮ bamboo top
  '⺮': {
    meaning: '竹子；多用於竹製品（竹字頭）',
    role: '形符',
    relatedChars: [
      { char: '第', meaning: '次序' },
      { char: '等', meaning: '等候' },
      { char: '節', meaning: '節日、節制' },
      { char: '篇', meaning: '篇章' },
      { char: '符', meaning: '符號' },
      { char: '管', meaning: '管理' },
      { char: '簡', meaning: '簡單' },
      { char: '筆', meaning: '筆記' },
    ],
  },

  // 車 vehicle
  '車': {
    meaning: '車輛、交通工具',
    role: '形符',
    relatedChars: [
      { char: '較', meaning: '比較' },
      { char: '轉', meaning: '轉動' },
      { char: '連', meaning: '相連' },
      { char: '輕', meaning: '輕盈' },
      { char: '庫', meaning: '倉庫' },
      { char: '輸', meaning: '輸送' },
      { char: '軍', meaning: '軍隊' },
      { char: '載', meaning: '裝載' },
    ],
  },

  // 頁 head / page
  '頁': {
    meaning: '頭部、面容（古寫象人頭形）',
    role: '形符',
    relatedChars: [
      { char: '題', meaning: '題目' },
      { char: '項', meaning: '頸項、項目' },
      { char: '頭', meaning: '頭部' },
      { char: '預', meaning: '預先' },
      { char: '須', meaning: '必須' },
      { char: '顧', meaning: '照顧' },
      { char: '顯', meaning: '顯示' },
      { char: '順', meaning: '順從' },
    ],
  },

  // 攵 strike / action (變體 of 攴)
  '攵': {
    meaning: '手持器具敲打；多表動作（反文旁）',
    role: '形符',
    relatedChars: [
      { char: '數', meaning: '數量' },
      { char: '教', meaning: '教導' },
      { char: '變', meaning: '改變' },
      { char: '故', meaning: '緣故' },
      { char: '效', meaning: '效果' },
      { char: '放', meaning: '放開' },
      { char: '改', meaning: '改變' },
      { char: '救', meaning: '救助' },
    ],
  },

  // 馬 horse
  '馬': {
    meaning: '馬；與騎乘、奔跑有關',
    role: '形符',
    relatedChars: [
      { char: '媽', meaning: '媽媽' },
      { char: '驗', meaning: '檢驗' },
      { char: '嗎', meaning: '疑問助詞' },
      { char: '驚', meaning: '驚訝' },
      { char: '騙', meaning: '欺騙' },
      { char: '駕', meaning: '駕駛' },
      { char: '騎', meaning: '騎乘' },
      { char: '罵', meaning: '責罵' },
    ],
  },

  // 門 gate
  '門': {
    meaning: '門戶、建築出入口',
    role: '形符',
    relatedChars: [
      { char: '們', meaning: '複數詞尾' },
      { char: '問', meaning: '詢問' },
      { char: '開', meaning: '打開' },
      { char: '間', meaning: '空間' },
      { char: '關', meaning: '關閉' },
      { char: '聞', meaning: '聽見' },
      { char: '閃', meaning: '閃爍' },
      { char: '閒', meaning: '閒暇' },
    ],
  },

  // 罒 net
  '罒': {
    meaning: '網狀物（网字變體）',
    role: '形符',
    relatedChars: [
      { char: '眾', meaning: '眾人' },
      { char: '夢', meaning: '夢境' },
      { char: '德', meaning: '道德' },
      { char: '羅', meaning: '羅列' },
      { char: '置', meaning: '放置' },
      { char: '罪', meaning: '罪行' },
      { char: '罰', meaning: '處罰' },
      { char: '罵', meaning: '責罵' },
    ],
  },

  // 肖 resemble (phonetic)
  '肖': {
    meaning: '相似、像（常作聲符）',
    role: '聲符',
    relatedChars: [
      { char: '消', meaning: '消失' },
      { char: '稍', meaning: '稍微' },
      { char: '銷', meaning: '銷售' },
      { char: '悄', meaning: '悄悄' },
      { char: '哨', meaning: '哨子' },
      { char: '削', meaning: '削減' },
    ],
  },

  // 丷 diverging strokes
  '丷': {
    meaning: '分開的兩點（常見於字首裝飾）',
    role: '部件',
    relatedChars: [
      { char: '前', meaning: '前面' },
      { char: '並', meaning: '並且' },
      { char: '弟', meaning: '弟弟' },
      { char: '曾', meaning: '曾經' },
      { char: '半', meaning: '一半' },
      { char: '善', meaning: '良善' },
      { char: '乎', meaning: '語氣助詞' },
      { char: '幸', meaning: '幸福' },
    ],
  },

  // 尚 still / esteem (phonetic)
  '尚': {
    meaning: '崇尚、還（常作聲符）',
    role: '聲符',
    relatedChars: [
      { char: '常', meaning: '經常' },
      { char: '當', meaning: '擔當' },
      { char: '掌', meaning: '手掌' },
      { char: '嘗', meaning: '品嘗' },
      { char: '賞', meaning: '欣賞' },
      { char: '堂', meaning: '廳堂' },
      { char: '躺', meaning: '躺下' },
    ],
  },

  // 包 wrap
  '包': {
    meaning: '包裹、包覆',
    role: '聲符',
    relatedChars: [
      { char: '跑', meaning: '奔跑' },
      { char: '抱', meaning: '懷抱' },
      { char: '飽', meaning: '吃飽' },
      { char: '胞', meaning: '細胞' },
      { char: '泡', meaning: '泡沫' },
      { char: '苞', meaning: '花苞' },
    ],
  },

  // 者 one who / helper particle
  '者': {
    meaning: '「⋯的人」的助詞；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '都', meaning: '首都、都市' },
      { char: '著', meaning: '著作、顯著' },
      { char: '緒', meaning: '頭緒' },
      { char: '署', meaning: '署名' },
      { char: '煮', meaning: '烹煮' },
      { char: '暑', meaning: '暑熱' },
      { char: '諸', meaning: '各個' },
    ],
  },

  // 圭 jade tablet
  '圭': {
    meaning: '古代玉器（圭璋）；作聲符',
    role: '聲符',
    relatedChars: [
      { char: '鞋', meaning: '鞋子' },
      { char: '哇', meaning: '驚嘆語氣' },
      { char: '佳', meaning: '美好' },
      { char: '街', meaning: '街道' },
      { char: '蛙', meaning: '青蛙' },
      { char: '封', meaning: '封閉' },
      { char: '桂', meaning: '桂花' },
    ],
  },

  // 且 moreover
  '且': {
    meaning: '並列、況且；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '助', meaning: '幫助' },
      { char: '組', meaning: '組成' },
      { char: '姐', meaning: '姐姐' },
      { char: '祖', meaning: '祖先' },
      { char: '宜', meaning: '適宜' },
      { char: '阻', meaning: '阻擋' },
    ],
  },

  // 各 each
  '各': {
    meaning: '各自；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '路', meaning: '道路' },
      { char: '格', meaning: '格式' },
      { char: '客', meaning: '客人' },
      { char: '略', meaning: '省略' },
      { char: '落', meaning: '落下' },
    ],
  },

  // 糸 silk thread
  '糸': {
    meaning: '絲線、繩索',
    role: '形符',
    relatedChars: [
      { char: '素', meaning: '素色、平素' },
      { char: '絲', meaning: '絲線' },
      { char: '緊', meaning: '緊密' },
      { char: '索', meaning: '繩索、探索' },
      { char: '繁', meaning: '繁多' },
      { char: '累', meaning: '累積' },
    ],
  },

  // 丁 nail / male adult
  '丁': {
    meaning: '鐵釘、壯丁；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '打', meaning: '敲打' },
      { char: '頂', meaning: '頂端' },
      { char: '寧', meaning: '安寧' },
      { char: '盯', meaning: '盯住' },
      { char: '釘', meaning: '釘子' },
      { char: '叮', meaning: '叮咬' },
      { char: '訂', meaning: '訂立' },
    ],
  },

  // 也 also
  '也': {
    meaning: '助詞「也」；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '他', meaning: '第三人稱' },
      { char: '地', meaning: '土地' },
      { char: '她', meaning: '女性第三人稱' },
      { char: '施', meaning: '施行' },
      { char: '牠', meaning: '動物第三人稱' },
      { char: '池', meaning: '池塘' },
    ],
  },

  // 分 divide
  '分': {
    meaning: '分開、分配',
    role: '聲符',
    relatedChars: [
      { char: '份', meaning: '份量' },
      { char: '紛', meaning: '紛亂' },
      { char: '貧', meaning: '貧窮' },
      { char: '粉', meaning: '粉末' },
      { char: '扮', meaning: '扮演' },
      { char: '芬', meaning: '芬芳' },
    ],
  },

  // 犬 dog
  '犬': {
    meaning: '狗；與動物、追獵有關',
    role: '形符',
    relatedChars: [
      { char: '狀', meaning: '狀態' },
      { char: '突', meaning: '突然' },
      { char: '器', meaning: '器具' },
      { char: '獎', meaning: '獎賞' },
      { char: '伏', meaning: '伏臥' },
      { char: '哭', meaning: '哭泣' },
      { char: '獻', meaning: '奉獻' },
    ],
  },

  // 古 ancient
  '古': {
    meaning: '古老、古代；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '故', meaning: '緣故' },
      { char: '苦', meaning: '痛苦' },
      { char: '居', meaning: '居住' },
      { char: '固', meaning: '堅固' },
      { char: '估', meaning: '估計' },
      { char: '胡', meaning: '胡亂' },
      { char: '枯', meaning: '枯萎' },
    ],
  },

  // 令 command
  '令': {
    meaning: '命令；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '命', meaning: '命令、生命' },
      { char: '冷', meaning: '寒冷' },
      { char: '領', meaning: '領導' },
      { char: '零', meaning: '零星' },
      { char: '齡', meaning: '年齡' },
      { char: '鈴', meaning: '鈴鐺' },
    ],
  },

  // 直 straight
  '直': {
    meaning: '筆直、正直',
    role: '聲符',
    relatedChars: [
      { char: '真', meaning: '真實' },
      { char: '植', meaning: '種植' },
      { char: '值', meaning: '價值' },
      { char: '置', meaning: '放置' },
      { char: '殖', meaning: '繁殖' },
    ],
  },

  // 巴 cling
  '巴': {
    meaning: '緊貼、盼望',
    role: '聲符',
    relatedChars: [
      { char: '把', meaning: '把握' },
      { char: '爸', meaning: '爸爸' },
      { char: '吧', meaning: '語氣助詞' },
      { char: '爬', meaning: '攀爬' },
    ],
  },

  // 果 fruit
  '果': {
    meaning: '果實、結果',
    role: '聲符',
    relatedChars: [
      { char: '課', meaning: '課程' },
      { char: '棵', meaning: '量詞（一棵樹）' },
      { char: '顆', meaning: '量詞（一顆球）' },
    ],
  },

  // 乂 cut grass / govern
  '乂': {
    meaning: '割草、治理（古「艾」字）',
    role: '部件',
    relatedChars: [
      { char: '希', meaning: '希望' },
      { char: '父', meaning: '父親' },
      { char: '凶', meaning: '凶險' },
      { char: '交', meaning: '交會' },
      { char: '史', meaning: '歷史' },
      { char: '艾', meaning: '艾草' },
    ],
  },

  // 占 divine
  '占': {
    meaning: '占卜、佔有',
    role: '聲符',
    relatedChars: [
      { char: '點', meaning: '點滴' },
      { char: '站', meaning: '站立' },
      { char: '店', meaning: '店舖' },
      { char: '貼', meaning: '貼近' },
      { char: '佔', meaning: '佔據' },
      { char: '黏', meaning: '黏貼' },
    ],
  },

  // 乚 hidden / hook stroke
  '乚': {
    meaning: '隱藏；乙的變體（常為末筆）',
    role: '部件',
    relatedChars: [
      { char: '已', meaning: '已經' },
      { char: '孔', meaning: '孔洞' },
      { char: '尺', meaning: '尺寸' },
      { char: '亂', meaning: '混亂' },
      { char: '乳', meaning: '乳汁' },
    ],
  },

  // 爫 claw / grab
  '爫': {
    meaning: '手抓取（爪字變體）',
    role: '形符',
    relatedChars: [
      { char: '為', meaning: '作為' },
      { char: '受', meaning: '接受' },
      { char: '愛', meaning: '愛護' },
      { char: '爭', meaning: '爭取' },
      { char: '亂', meaning: '混亂' },
      { char: '采', meaning: '採集' },
    ],
  },

  // 可 can
  '可': {
    meaning: '可以、贊同',
    role: '聲符',
    relatedChars: [
      { char: '何', meaning: '何時' },
      { char: '阿', meaning: '稱謂字首' },
      { char: '哥', meaning: '哥哥' },
      { char: '奇', meaning: '奇特' },
      { char: '河', meaning: '河流' },
    ],
  },

  // 共 together
  '共': {
    meaning: '共同、一起',
    role: '聲符',
    relatedChars: [
      { char: '供', meaning: '供給' },
      { char: '洪', meaning: '洪水' },
      { char: '恭', meaning: '恭敬' },
      { char: '哄', meaning: '哄騙' },
    ],
  },

  // 莫 do not / dusk
  '莫': {
    meaning: '不要；原為黃昏（暮）',
    role: '聲符',
    relatedChars: [
      { char: '模', meaning: '模型、模仿' },
      { char: '慕', meaning: '羨慕' },
      { char: '漠', meaning: '沙漠' },
      { char: '摸', meaning: '撫摸' },
      { char: '膜', meaning: '薄膜' },
      { char: '墓', meaning: '墳墓' },
      { char: '寞', meaning: '寂寞' },
      { char: '幕', meaning: '帷幕' },
    ],
  },

  // 台 platform
  '台': {
    meaning: '平台；台語中亦表敬稱',
    role: '聲符',
    relatedChars: [
      { char: '始', meaning: '開始' },
      { char: '治', meaning: '治理' },
      { char: '抬', meaning: '抬起' },
      { char: '胎', meaning: '胎兒' },
      { char: '颱', meaning: '颱風' },
    ],
  },

  // 巠 underground stream
  '巠': {
    meaning: '地下水流（常作聲符）',
    role: '聲符',
    relatedChars: [
      { char: '經', meaning: '經過、經書' },
      { char: '輕', meaning: '輕盈' },
      { char: '徑', meaning: '小徑' },
    ],
  },

  // 魚 fish
  '魚': {
    meaning: '魚類；與水產有關',
    role: '形符',
    relatedChars: [
      { char: '鯨', meaning: '鯨魚' },
      { char: '鮮', meaning: '新鮮' },
      { char: '漁', meaning: '捕魚' },
      { char: '魯', meaning: '粗魯' },
    ],
  },

  // 堇 yellow clay
  '堇': {
    meaning: '黃黏土；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '難', meaning: '困難' },
      { char: '僅', meaning: '僅僅' },
      { char: '嘆', meaning: '嘆息' },
      { char: '艱', meaning: '艱難' },
      { char: '勤', meaning: '勤勞' },
      { char: '謹', meaning: '謹慎' },
      { char: '漢', meaning: '漢朝、漢字' },
    ],
  },

  // 僉 all
  '僉': {
    meaning: '眾人、全部；常作聲符',
    role: '聲符',
    relatedChars: [
      { char: '驗', meaning: '檢驗' },
      { char: '險', meaning: '危險' },
      { char: '檢', meaning: '檢查' },
      { char: '臉', meaning: '臉龐' },
    ],
  },

  // 少 few
  '少': {
    meaning: '少量、稀少',
    role: '聲符',
    relatedChars: [
      { char: '省', meaning: '省略' },
      { char: '秒', meaning: '秒數' },
      { char: '沙', meaning: '沙子' },
      { char: '妙', meaning: '奇妙' },
      { char: '吵', meaning: '吵鬧' },
      { char: '炒', meaning: '炒菜' },
    ],
  },

  // 合 combine
  '合': {
    meaning: '合起、聚集',
    role: '聲符',
    relatedChars: [
      { char: '給', meaning: '給予' },
      { char: '答', meaning: '回答' },
      { char: '拿', meaning: '拿取' },
      { char: '哈', meaning: '大笑' },
      { char: '恰', meaning: '恰好' },
      { char: '鴿', meaning: '鴿子' },
    ],
  },

  // 余 surplus / I (archaic)
  '余': {
    meaning: '多餘；古時第一人稱',
    role: '聲符',
    relatedChars: [
      { char: '除', meaning: '除去' },
      { char: '敘', meaning: '敘述' },
      { char: '餘', meaning: '剩餘' },
      { char: '途', meaning: '路途' },
      { char: '徐', meaning: '緩慢' },
    ],
  },

  // 亡 flee / lose
  '亡': {
    meaning: '逃亡、失去',
    role: '聲符',
    relatedChars: [
      { char: '望', meaning: '希望' },
      { char: '忙', meaning: '忙碌' },
      { char: '贏', meaning: '勝利' },
      { char: '忘', meaning: '遺忘' },
      { char: '妄', meaning: '虛妄' },
    ],
  },

  // 予 give / I
  '予': {
    meaning: '給予；亦為第一人稱',
    role: '聲符',
    relatedChars: [
      { char: '預', meaning: '預備' },
      { char: '野', meaning: '原野' },
      { char: '序', meaning: '次序' },
      { char: '舒', meaning: '舒展' },
    ],
  },

  // 林 woods
  '林': {
    meaning: '樹林；雙木成林',
    role: '部件',
    relatedChars: [
      { char: '楚', meaning: '清楚' },
      { char: '麻', meaning: '麻布' },
      { char: '淋', meaning: '淋浴' },
      { char: '禁', meaning: '禁止' },
      { char: '鬱', meaning: '憂鬱' },
    ],
  },

  // 乃 thereupon
  '乃': {
    meaning: '於是、就；古代連詞',
    role: '部件',
    relatedChars: [
      { char: '及', meaning: '及時' },
      { char: '仍', meaning: '仍然' },
      { char: '奶', meaning: '奶水' },
      { char: '秀', meaning: '秀美' },
      { char: '孕', meaning: '懷孕' },
    ],
  },

  // 旦 dawn
  '旦': {
    meaning: '清晨、日出地平線',
    role: '部件',
    relatedChars: [
      { char: '但', meaning: '但是' },
      { char: '量', meaning: '數量' },
      { char: '查', meaning: '查詢' },
      { char: '坦', meaning: '坦白' },
    ],
  },

  // 乍 suddenly
  '乍': {
    meaning: '忽然、初始',
    role: '聲符',
    relatedChars: [
      { char: '作', meaning: '作為' },
      { char: '怎', meaning: '怎麼' },
      { char: '炸', meaning: '爆炸' },
      { char: '昨', meaning: '昨日' },
    ],
  },
};

// ---------------------------------------------------------------------------
// Character decomposition database (常用字部件拆解)
// ---------------------------------------------------------------------------

export const charDecomposition: Record<string, CharDecomposition> = {
  '明': {
    formula: '日 + 月',
    components: [
      { radical: '日', role: '形符', label: '太陽' },
      { radical: '月', role: '形符', label: '月亮' },
    ],
  },
  '清': {
    formula: '氵 + 青',
    components: [
      { radical: '氵', role: '形符', label: '水旁' },
      { radical: '青', role: '聲符', label: '讀音' },
    ],
  },
  '情': {
    formula: '忄 + 青',
    components: [
      { radical: '忄', role: '形符', label: '心旁' },
      { radical: '青', role: '聲符', label: '讀音' },
    ],
  },
  '晴': {
    formula: '日 + 青',
    components: [
      { radical: '日', role: '形符', label: '太陽' },
      { radical: '青', role: '聲符', label: '讀音' },
    ],
  },
  '請': {
    formula: '訁 + 青',
    components: [
      { radical: '訁', role: '形符', label: '言旁' },
      { radical: '青', role: '聲符', label: '讀音' },
    ],
  },
  '樹': {
    formula: '木 + 尌',
    components: [
      { radical: '木', role: '形符', label: '木旁' },
      { radical: '尌', role: '聲符', label: '讀音' },
    ],
  },
  '林': {
    formula: '木 + 木',
    components: [
      { radical: '木', role: '部件', label: '樹木' },
      { radical: '木', role: '部件', label: '樹木' },
    ],
  },
  '森': {
    formula: '木 + 木 + 木',
    components: [
      { radical: '木', role: '部件', label: '樹木' },
      { radical: '木', role: '部件', label: '樹木' },
      { radical: '木', role: '部件', label: '樹木' },
    ],
  },
  '花': {
    formula: '艹 + 化',
    components: [
      { radical: '艹', role: '形符', label: '草頭' },
      { radical: '化', role: '聲符', label: '讀音' },
    ],
  },
  '草': {
    formula: '艹 + 早',
    components: [
      { radical: '艹', role: '形符', label: '草頭' },
      { radical: '早', role: '聲符', label: '讀音' },
    ],
  },
  '海': {
    formula: '氵 + 每',
    components: [
      { radical: '氵', role: '形符', label: '水旁' },
      { radical: '每', role: '聲符', label: '讀音' },
    ],
  },
  '河': {
    formula: '氵 + 可',
    components: [
      { radical: '氵', role: '形符', label: '水旁' },
      { radical: '可', role: '聲符', label: '讀音' },
    ],
  },
  '湖': {
    formula: '氵 + 胡',
    components: [
      { radical: '氵', role: '形符', label: '水旁' },
      { radical: '胡', role: '聲符', label: '讀音' },
    ],
  },
  '說': {
    formula: '訁 + 兌',
    components: [
      { radical: '訁', role: '形符', label: '言旁' },
      { radical: '兌', role: '聲符', label: '讀音' },
    ],
  },
  '話': {
    formula: '訁 + 舌',
    components: [
      { radical: '訁', role: '形符', label: '言旁' },
      { radical: '舌', role: '部件', label: '舌頭' },
    ],
  },
  '快': {
    formula: '忄 + 夬',
    components: [
      { radical: '忄', role: '形符', label: '心旁' },
      { radical: '夬', role: '聲符', label: '讀音' },
    ],
  },
  '慢': {
    formula: '忄 + 曼',
    components: [
      { radical: '忄', role: '形符', label: '心旁' },
      { radical: '曼', role: '聲符', label: '讀音' },
    ],
  },
  '想': {
    formula: '相 + 心',
    components: [
      { radical: '相', role: '聲符', label: '讀音' },
      { radical: '心', role: '形符', label: '心' },
    ],
  },
  '愛': {
    formula: '爫 + 心 + 友',
    components: [
      { radical: '爫', role: '部件', label: '爪部' },
      { radical: '心', role: '形符', label: '心' },
      { radical: '友', role: '部件', label: '友愛' },
    ],
  },
  '您': {
    formula: '你 + 心',
    components: [
      { radical: '你', role: '部件', label: '你' },
      { radical: '心', role: '形符', label: '心' },
    ],
  },
  '跑': {
    formula: '足 + 包',
    components: [
      { radical: '足', role: '形符', label: '足旁' },
      { radical: '包', role: '聲符', label: '讀音' },
    ],
  },
  '跳': {
    formula: '足 + 兆',
    components: [
      { radical: '足', role: '形符', label: '足旁' },
      { radical: '兆', role: '聲符', label: '讀音' },
    ],
  },
  '吃': {
    formula: '口 + 乞',
    components: [
      { radical: '口', role: '形符', label: '口旁' },
      { radical: '乞', role: '聲符', label: '讀音' },
    ],
  },
  '喝': {
    formula: '口 + 曷',
    components: [
      { radical: '口', role: '形符', label: '口旁' },
      { radical: '曷', role: '聲符', label: '讀音' },
    ],
  },
  '唱': {
    formula: '口 + 昌',
    components: [
      { radical: '口', role: '形符', label: '口旁' },
      { radical: '昌', role: '聲符', label: '讀音' },
    ],
  },
  '媽': {
    formula: '女 + 馬',
    components: [
      { radical: '女', role: '形符', label: '女旁' },
      { radical: '馬', role: '聲符', label: '讀音' },
    ],
  },
  '姐': {
    formula: '女 + 且',
    components: [
      { radical: '女', role: '形符', label: '女旁' },
      { radical: '且', role: '聲符', label: '讀音' },
    ],
  },
  '妹': {
    formula: '女 + 末',
    components: [
      { radical: '女', role: '形符', label: '女旁' },
      { radical: '末', role: '聲符', label: '讀音' },
    ],
  },
  '雪': {
    formula: '雨 + 彐',
    components: [
      { radical: '雨', role: '形符', label: '雨字頭' },
      { radical: '彐', role: '部件', label: '掃帚形' },
    ],
  },
  '雲': {
    formula: '雨 + 云',
    components: [
      { radical: '雨', role: '形符', label: '雨字頭' },
      { radical: '云', role: '聲符', label: '讀音' },
    ],
  },
  '好': {
    formula: '女 + 子',
    components: [
      { radical: '女', role: '形符', label: '女旁' },
      { radical: '子', role: '部件', label: '孩子' },
    ],
  },
  '休': {
    formula: '亻 + 木',
    components: [
      { radical: '亻', role: '形符', label: '人旁' },
      { radical: '木', role: '部件', label: '樹木' },
    ],
  },
  '信': {
    formula: '亻 + 言',
    components: [
      { radical: '亻', role: '形符', label: '人旁' },
      { radical: '言', role: '部件', label: '說話' },
    ],
  },
  '勇': {
    formula: '甬 + 力',
    components: [
      { radical: '甬', role: '聲符', label: '讀音' },
      { radical: '力', role: '形符', label: '力量' },
    ],
  },
  '早': {
    formula: '日 + 十',
    components: [
      { radical: '日', role: '形符', label: '太陽' },
      { radical: '十', role: '部件', label: '草芽' },
    ],
  },
  '春': {
    formula: '三 + 人 + 日',
    components: [
      { radical: '三', role: '部件', label: '草木' },
      { radical: '人', role: '部件', label: '人' },
      { radical: '日', role: '形符', label: '太陽' },
    ],
  },
  '路': {
    formula: '足 + 各',
    components: [
      { radical: '足', role: '形符', label: '足旁' },
      { radical: '各', role: '聲符', label: '讀音' },
    ],
  },
  '謝': {
    formula: '訁 + 射',
    components: [
      { radical: '訁', role: '形符', label: '言旁' },
      { radical: '射', role: '聲符', label: '讀音' },
    ],
  },
  '認': {
    formula: '訁 + 忍',
    components: [
      { radical: '訁', role: '形符', label: '言旁' },
      { radical: '忍', role: '聲符', label: '讀音' },
    ],
  },
  '熱': {
    formula: '埶 + 灬',
    components: [
      { radical: '埶', role: '聲符', label: '讀音' },
      { radical: '灬', role: '形符', label: '火底' },
    ],
  },
  '照': {
    formula: '昭 + 灬',
    components: [
      { radical: '昭', role: '聲符', label: '讀音' },
      { radical: '灬', role: '形符', label: '火底' },
    ],
  },
  '銀': {
    formula: '金 + 艮',
    components: [
      { radical: '金', role: '形符', label: '金旁' },
      { radical: '艮', role: '聲符', label: '讀音' },
    ],
  },
  '鐵': {
    formula: '金 + 𢧤',
    components: [
      { radical: '金', role: '形符', label: '金旁' },
      { radical: '𢧤', role: '聲符', label: '讀音' },
    ],
  },
};

// ---------------------------------------------------------------------------
// Radical meanings JSON (lazy-loaded open-data fallback)
// Sources: moedict (zh-TW) + makemeahanzi + branneman 214 radicals
// Schema: v2.0 — every field has *Source + *SourceUrl tracking
// Generated by: scripts/build-radical-database.py (saigyo excluded: zh-CN only)
// ---------------------------------------------------------------------------

interface RadicalMeaningEntry {
  meaning: string;
  meaningSource: string;
  meaningSourceUrl: string;
  englishMeaning: string;
  strokeCount: number;
  baseRadical?: string;
  relatedChars: string[];
  relatedCharsSource: string;
  relatedCharsSourceUrl?: string;
}

let _radicalMeaningsCache: Record<string, RadicalMeaningEntry> | null = null;

/**
 * Asynchronously loads the aggregated radical meanings database and caches it.
 * Safe to call multiple times — only loads once.
 */
export async function initRadicalMeanings(): Promise<void> {
  if (_radicalMeaningsCache !== null) return;
  const mod = await import('./radical-meanings.json');
  // Exclude the _metadata key from the cache
  const { _metadata: _, ...entries } = mod.default as Record<string, unknown>;
  _radicalMeaningsCache = entries as Record<string, RadicalMeaningEntry>;
}

// ---------------------------------------------------------------------------
// Generated decomposition data (lazy-loaded to avoid bundle bloat)
// Populated once by initGeneratedDecompositions(); null = not yet loaded.
// ---------------------------------------------------------------------------

let _generatedCache: Record<string, CharDecomposition> | null = null;

/**
 * Asynchronously loads the generated decomposition database (~700KB raw,
 * ~48KB gzipped) and caches it in memory.  Call this once before rendering
 * RadicalDecomposition to maximise coverage.
 *
 * Safe to call multiple times — only fetches once.
 */
export async function initGeneratedDecompositions(): Promise<void> {
  if (_generatedCache !== null) return;
  const mod = await import('./decompositions-generated.json');
  _generatedCache = mod.default as Record<string, CharDecomposition>;
}

// ---------------------------------------------------------------------------
// Helper: look up decomposition for a character
// ---------------------------------------------------------------------------

/**
 * Returns decomposition for a character.
 * Priority: hand-curated (charDecomposition) → generated (decompositions-generated.json).
 * Returns null if not found in either source.
 */
export function getDecomposition(char: string): CharDecomposition | null {
  // Hand-curated entries take highest priority
  if (charDecomposition[char]) return charDecomposition[char];
  // Fall back to generated data if loaded
  if (_generatedCache && _generatedCache[char]) return _generatedCache[char];
  return null;
}

/** Returns the source of decomposition data for a character */
export function getDecompositionSource(char: string): 'hand-curated' | 'generated' | null {
  if (charDecomposition[char]) return 'hand-curated';
  if (_generatedCache && _generatedCache[char]) return 'generated';
  return null;
}

/**
 * Returns related characters for a given radical.
 * Priority: hand-curated (radicalMap) → radical-meanings.json open-data.
 * Excludes the source character itself from the list.
 */
export function getRelatedChars(radical: string, excludeChar?: string): RelatedChar[] {
  // Hand-curated first
  const info = radicalMap[radical];
  if (info) {
    const filtered = excludeChar
      ? info.relatedChars.filter(r => r.char !== excludeChar)
      : info.relatedChars;
    // Deduplicate by char
    const seen = new Set<string>();
    return filtered.filter(r => { if (seen.has(r.char)) return false; seen.add(r.char); return true; });
  }
  // Fall back to open-data JSON (characters without individual meanings)
  if (_radicalMeaningsCache) {
    const entry = _radicalMeaningsCache[radical];
    if (entry && entry.relatedChars.length > 0) {
      const seen = new Set<string>();
      const chars: RelatedChar[] = entry.relatedChars
        .filter(c => c !== excludeChar && !seen.has(c) && (seen.add(c), true))
        .map(c => ({ char: c, meaning: '' }));
      return chars;
    }
  }
  return [];
}

/**
 * Returns radical info (meaning + role).
 * Priority: hand-curated (radicalMap) → radical-meanings.json open-data.
 */
export function getRadicalInfo(radical: string): RadicalInfo | null {
  // Hand-curated entries take highest priority
  if (radicalMap[radical]) return radicalMap[radical];
  // Fall back to open-data JSON
  if (_radicalMeaningsCache) {
    const entry = _radicalMeaningsCache[radical];
    if (entry) {
      return {
        meaning: entry.meaning,
        role: '形符',
        relatedChars: entry.relatedChars.map(c => ({ char: c, meaning: '' })),
      };
    }
  }
  return null;
}
