#!/usr/bin/env python3
"""Build specs/registry.yaml from every module's INTENT.md frontmatter.

The registry is the cheap "Level-1 discovery" index an AI (or a human) loads
first: a small list of every spec module + what code/data it owns + where its
human spec and executable spec live. No per-module prose is loaded until the
relevant module is matched.

The registry is AUTO-GENERATED — never hand-edit it. CI runs `--check` to fail
if the committed registry has drifted from the modules on disk.

Usage:
    python specs/build_registry.py            # regenerate specs/registry.yaml
    python specs/build_registry.py --check     # exit 1 if registry is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

SPECS_DIR = Path(__file__).resolve().parent
MODULES_DIR = SPECS_DIR / "modules"
REGISTRY = SPECS_DIR / "registry.yaml"

# Fields lifted from each INTENT.md frontmatter into the registry.
_FIELDS = [
    "spec_id",
    "module",
    "title",
    "stability",
    "canonical_source",
    "owns_code",
    "owns_data",
    "spec_tests",
    "fixtures",
    "probes",
    "related_issues",
    "source_meetings",
    "last_reviewed",
    "owner",
]

_HEADER = (
    "# AUTO-GENERATED by specs/build_registry.py — DO NOT EDIT BY HAND.\n"
    "# Run `python specs/build_registry.py` after changing any module INTENT.md.\n"
)


def _read_frontmatter(intent_path: Path) -> dict:
    text = intent_path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{intent_path} has no YAML frontmatter")
    _, fm, _ = text.split("---", 2)
    data = yaml.safe_load(fm) or {}
    if "spec_id" not in data:
        raise ValueError(f"{intent_path} frontmatter missing required 'spec_id'")
    return data


def build() -> str:
    modules = []
    for intent in sorted(MODULES_DIR.glob("*/INTENT.md")):
        fm = _read_frontmatter(intent)
        entry = {k: fm[k] for k in _FIELDS if k in fm}
        entry["intent"] = str(intent.relative_to(SPECS_DIR.parent))
        modules.append(entry)
    payload = {"modules": modules}
    body = yaml.safe_dump(payload, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return _HEADER + body


def main(argv: list[str]) -> int:
    rendered = build()
    if "--check" in argv:
        if not REGISTRY.exists():
            print("registry.yaml missing — run: python specs/build_registry.py", file=sys.stderr)
            return 1
        current = REGISTRY.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "registry.yaml is STALE — module INTENT.md changed without "
                "regenerating. Run: python specs/build_registry.py",
                file=sys.stderr,
            )
            return 1
        print("registry.yaml is up to date.")
        return 0
    REGISTRY.write_text(rendered, encoding="utf-8")
    n = len(yaml.safe_load(rendered)["modules"])
    print(f"wrote {REGISTRY.relative_to(SPECS_DIR.parent)} ({n} module(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
