#!/usr/bin/env python3
"""Build specs/registry.yaml from every module's INTENT.md frontmatter.

The registry is the cheap "Level-1 discovery" index an AI (or a human) loads
first: a small list of every spec module + what code/data it owns + where its
human spec and executable spec live. No per-module prose is loaded until the
relevant module is matched.

The registry is AUTO-GENERATED — never hand-edit it. CI runs `--check` to fail
if the committed registry has drifted from the modules on disk.

Usage:
    python specs/build_registry.py            # regenerate specs/registry.yaml
    python specs/build_registry.py --check     # exit 1 if registry is stale

Lock 2 (pointer-rot guard):
    --check also verifies that every path listed under `legacy_tests:` in any
    module's INTENT.md actually exists on disk.  A dangling pointer causes an
    immediate, loud failure so pointer-rot is caught at CI time, not silently
    after weeks of drift.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

SPECS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SPECS_DIR.parent
MODULES_DIR = SPECS_DIR / "modules"
REGISTRY = SPECS_DIR / "registry.yaml"

# Fields lifted from each INTENT.md frontmatter into the registry.
_FIELDS = [
    "spec_id",
    "module",
    "title",
    "stability",
    "canonical_source",
    "owns_code",
    "owns_data",
    "spec_tests",
    "legacy_tests",
    "fixtures",
    "probes",
    "related_issues",
    "source_meetings",
    "last_reviewed",
    "owner",
]

_HEADER = (
    "# AUTO-GENERATED by specs/build_registry.py — DO NOT EDIT BY HAND.\n"
    "# Run `python specs/build_registry.py` after changing any module INTENT.md.\n"
)


def _read_frontmatter(intent_path: Path) -> dict:
    text = intent_path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{intent_path} has no YAML frontmatter")
    _, fm, _ = text.split("---", 2)
    data = yaml.safe_load(fm) or {}
    if "spec_id" not in data:
        raise ValueError(f"{intent_path} frontmatter missing required 'spec_id'")
    return data


def build() -> str:
    modules = []
    for intent in sorted(MODULES_DIR.glob("*/INTENT.md")):
        fm = _read_frontmatter(intent)
        entry = {k: fm[k] for k in _FIELDS if k in fm}
        entry["intent"] = str(intent.relative_to(SPECS_DIR.parent))
        modules.append(entry)
    payload = {"modules": modules}
    body = yaml.safe_dump(payload, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return _HEADER + body


def _collect_legacy_test_paths() -> list[tuple[str, str]]:
    """Return [(module_spec_id, path_str), ...] for all legacy_tests entries."""
    paths = []
    for intent in sorted(MODULES_DIR.glob("*/INTENT.md")):
        fm = _read_frontmatter(intent)
        legacy = fm.get("legacy_tests") or []
        spec_id = fm.get("spec_id", str(intent))
        for p in legacy:
            paths.append((spec_id, p))
    return paths


def _check_legacy_test_paths(errors: list[str]) -> None:
    """Lock 2: assert every legacy_tests path EXISTS and is pytest-collectable.

    Appends human-readable error strings to `errors` for any violation.
    A missing file is always an error.  A non-collectable file (e.g. import
    error) is reported as a warning printed to stderr but does NOT block the
    check — this avoids false positives in CI environments where the full
    backend deps aren't installed.
    """
    for spec_id, rel_path in _collect_legacy_test_paths():
        abs_path = REPO_ROOT / rel_path
        if not abs_path.exists():
            errors.append(
                f"[pointer-rot] {spec_id}: legacy_tests path does not exist: {rel_path}"
            )
            continue
        # Optionally verify pytest can collect it (best-effort; skip if pytest unavailable)
        try:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", "--collect-only", "-q", str(abs_path)],
                capture_output=True,
                text=True,
                cwd=str(REPO_ROOT / "backend"),
                timeout=30,
            )
            # pytest --collect-only exits 0 (tests found), 5 (no tests collected), or 1+ (error)
            # We accept 0 and 5; reject 1-4 (collection errors, import errors, etc.)
            if result.returncode not in (0, 5):
                print(
                    f"  WARNING: {spec_id}: legacy_tests {rel_path} may have collection issues "
                    f"(pytest exit {result.returncode}) — check manually if in a full env",
                    file=sys.stderr,
                )
        except (FileNotFoundError, subprocess.TimeoutExpired):
            # pytest not available or timed out — skip collectability check silently
            pass


def main(argv: list[str]) -> int:
    rendered = build()
    if "--check" in argv:
        if not REGISTRY.exists():
            print("registry.yaml missing — run: python specs/build_registry.py", file=sys.stderr)
            return 1
        current = REGISTRY.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "registry.yaml is STALE — module INTENT.md changed without "
                "regenerating. Run: python specs/build_registry.py",
                file=sys.stderr,
            )
            return 1

        # Lock 2: pointer-rot guard — dangling legacy_tests paths fail loudly
        errors: list[str] = []
        _check_legacy_test_paths(errors)
        if errors:
            print("LEGACY_TESTS POINTER-ROT DETECTED:", file=sys.stderr)
            for err in errors:
                print(f"  {err}", file=sys.stderr)
            print(
                "Fix: update the legacy_tests: path in the relevant INTENT.md, "
                "then re-run: python specs/build_registry.py",
                file=sys.stderr,
            )
            return 1

        print("registry.yaml is up to date.")
        return 0
    REGISTRY.write_text(rendered, encoding="utf-8")
    n = len(yaml.safe_load(rendered)["modules"])
    print(f"wrote {REGISTRY.relative_to(SPECS_DIR.parent)} ({n} module(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
